services:
  hiveserver2:
    build:
      context: ../..
      dockerfile: docker/hive-ozone/Dockerfile
    image: my-hive-ozone:4.0.0
    environment:
      SERVICE_NAME: hiveserver2
    ports:
      - "10000:10000"
      - "10002:10002"
    networks:
      - ozone_net

networks:
  ozone_net:
    external: true
    name: ozone_default
